# Generated by Django 5.0.4 on 2024-04-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='pic',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
